services:
  web:
    build:
      ./apache
    container_name: container_php
    depends_on:
      - db
    volumes:
      - ./www:/var/www/html
    ports:
      - 8080:80

  db:
    image: mysql:5.7.25
    container_name: container_mysql
    volumes:
    - db_data:/var/lib/mysql
    - ./mycustom.cnf:/etc/mysql/conf.d/custom.cnf
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: Secret
      MYSQL_DATABASE: dbdockerapp
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - 3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: container_pma
    depends_on:
      - db
    ports:
      - 8083:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: Secret
      UPLOAD_LIMIT: 16M
volumes:
  db_data: